

### Fetch the PO
GET https://<subdomain>-dcbuild-purchase-srv.cfapps.ap10.hana.ondemand.com/service/purchaseOrderApp/PurchaseOrders
###

#### Call Actions updatespo to update the PO Status
POST https://<subdomain>-purchase-srv.cfapps.ap10.hana.ondemand.com/service/purchaseOrderApp/updatespo
Content-Type: application/json
{
"po":"PO-008",
"status":"Completed by Syed"
}
###