/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const cds = require('@sap/cds');
const LCAPApplicationService = require('@sap/low-code-event-handler');
const purchaseorders_Logic = require('./code/purchaseorders-logic');

//const { PurchaseOrders } = this.entities;

class purchaseOrderAppSrv extends LCAPApplicationService {
    async init() {

        this.on('UPDATE', 'PurchaseOrders', async (request, next) => {
            await purchaseorders_Logic(request);
            return next();
        });

        this.on('updatespo', async (req,res) => {
            console.log(req.data)
            const { PurchaseOrders } = this.entities;
            const result = await cds.run(SELECT.one(PurchaseOrders).columns("ID").where({ purchaseOrderNumber: req.data.po }));
            console.log("<<Data before Updation ", result.ID)

            const updatestatus = await cds.run(UPDATE(PurchaseOrders).where({ID: result.ID}).set({status:req.data.status}));

            console.log("<<< after updation ",updatestatus)
            
        });



        return super.init();
    }
}


module.exports = {
    purchaseOrderAppSrv
};